apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  namespace: {{.Release.Namespace }}
data:
  # Configuration for the Go application
  SCOPE_SERIALPORT: {{ .Values.scope.serialport }}
  {{- if .Values.scope.environments.fakescope }}
  SCOPE_ENVIRONMENTS_FAKESCOPE: "true"
  {{ else }}
  SCOPE_ENVIRONMENTS_FAKESCOPE: "false"
  {{- end }}