apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  namespace: {{.Release.Namespace }}
data:
  # Configuration for the Go application
  SCOPE_SERIALPORT: {{ .Values.scope.serialport }}
  SCOPE_ENVIRONMENTS_FAKESCOPE: {{ .Values.scope.environments.fakescope }}